// Remove "use client" here
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer"; // Adjust path as needed
import Header from "./components/Header"; // Adjust path as needed

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Musix Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Render Header, main content, and Footer */}
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}


// // app/layout.tsx
// import { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import Footer from "./components/Footer";
// import Header from "./components/Header";
// import SessionProviderWrapper from "./components/SessionProviderWrapper"; // Import the client wrapper

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Musix Zone",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className="h-full">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
//       >
//         {/* <SessionProviderWrapper> */}
//           <Header />
//           <main className="flex-grow">{children}</main>
//           <Footer />
//         {/* </SessionProviderWrapper> */}
//       </body>
//     </html>
//   );
// }

// "use client";

// import { SessionProvider } from "next-auth/react";
// import Header from "@/app/components/Header";
// import Footer from "@/app/components/Footer";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className="h-full">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
//       >
//         <SessionProvider>
//           <Header />
//           <main className="flex-grow">{children}</main>
//           <Footer />
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }
